### ISSUE TITLE
t2 command should be installed by default

### ISSUE THREAD

**Issue by mattsoftware** [tessel/openwrt-tessel#53]
When I ssh into the t2, I should be able to do things like 't2 update' directly on the tessel device.

**Comment by rwaldron** [comment]
Thanks for the feedback. 

t2-cli is designed for remote communication with a Tessel 2, not on-board command execution. It's just not as simple as saying "install by default": it would take months of work for the cli tool to be even a little bit usable on the board itself. 

That said, I think a subset tool could be developed that satisfied this request.

**Comment by mattsoftware** [comment]
could the connection not attach to itself over a loopback or similar? It just seems a natural fit now the t2 is a linux device to have tessel specific commands on the device as well.

My main reasoning for opening this request is I have a t2 which does not show up when running t2 list over wifi, which means I am unable run the update command. I can ssh into the device easily, so being able to run t2 update on the device would be a natural thing to want to do. 

It would also open the posability of controlling other t2's from a t2 itself.

Just some ideas that may be worth thinking about.

**Comment by rwaldron** [comment]
Again, it's just not that simple and it would take me actual hours to type out a complete explanation of why and as much as I want to be useful and informative to you, I'm also a human that needs to take time off for to ensure that I don't burn out. I like to do that on weekends, but I didn't want to leave you hanging until Monday ;)

> My main reasoning for opening this request is I have a t2 which does not show up when running t2 list over wifi, which means I am unable run the update command.

Then there is either a bug in the t2-cli, or some other issue preventing the expected behavior, but that doesn't mean that the solution is to impose another year's worth of work making a tool work in an environment that it was never intended to run in. 

Does this issue happen on home wifi or somewhere else? This is often caused by restrictions that are coming from router settings, in which device-to-device discovery is disallowed. We should really move this to https://github.com/tessel/t2-cli/issues

**Comment by johnnyman727** [comment]
Undiscoverable Tessels reported [here](https://github.com/tessel/t2-cli/issues/650).
